{% set name = "benchling-sdk" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/benchling-sdk-{{ version }}.tar.gz
  sha256: b321cb38ce0b7aa06b8b6850d55b078e13c016a127e3d7f4dc9dddc4e19cd1e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry
  run:
    - attrs >=20.1.0
    - backoff >=1.10.0,<2.0.0
    - dataclasses-json >=0.5.2,<0.6.0
    - httpx >=0.15.0,<0.16.0
    - python >=3.7,<4.0
    - python-dateutil >=2.8.0,<3.0.0
    - typing-extensions >=3.7.4,<4.0.0

test:
  imports:
    - benchling_api_client
    - benchling_api_client.api
  commands:
    - pip check
  requires:
    - pip
    # Removed "upper bound" pin on attrs for run, pinning here for "pip check"
    - attrs <21.0.0

about:
  home: https://pypi.org/project/benchling-sdk/
  summary: SDK for interacting with the Benchling Platform.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
