{% set name = "benchling-sdk" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0fb0adff14b0ee17d0efb47021161e8c08d520a260bec197752eddb1eeb557ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - pyyaml >=6.0,<7.0
    - attrs >=20.1.0,<23
    - backoff >=1.10.0,<2.0.0
    - benchling-api-client ==2.0.97
    - dataclasses-json >=0.5.2,<0.6.0
    - httpx >=0.23.0
    - python-dateutil >=2.8.0,<3.0.0
    - typing-extensions >=3.7.4,<5.0
    - psutil >=5.9.4,<6.0.0
    - jwcrypto >=1.4.2,<2.0.0
    - ordered-set >=4.1.0,<5.0.0
test:
  imports:
    - benchling_sdk
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://pypi.org/project/benchling-sdk/
  summary: SDK for interacting with the Benchling Platform.
  license: Apache-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - asford
    - PertuyF
    - jfolleas1
